name: Create release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Select increment (patch, minor, major)"
        required: true

permissions:
  id-token: write # Required for OIDC
  contents: write # For git operations

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false # never use caching in release builds
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm test
      - run: npm run release -- ${{ github.event.inputs.increment }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}
